In [1]:
import numpy as np
import pandas as pd 

In [16]:
# compare process time between numpy and list
from time import process_time

python_list = [i for i in range(10000000)]
start = process_time()
sum = [i + 5 for i in python_list]
end = process_time()

l = (end - start)
l

0.22423260999999983

In [17]:
numpy_array = np.array([i for i in range(10000000)])
s = process_time()
sum = numpy_array + 5
e = process_time()

n = (e - s)
n                      

0.06074327899999998

In [18]:
print(max([l,n]))

0.22423260999999983


In [60]:
type(n) # check the type 
print(numpy_array.ndim)# number of dimensions
print(numpy_array.size) # number of elements in an array
print(numpy_array.dtype) # checking the data type of the values in the array

1
10000000
int64


In [21]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [22]:
np_array.shape

(5,)

In [24]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [32]:
c = np.array([(1,2,3,4),(5,6,0,8)],dtype=float)
print(c)
print(c.dtype)

[[1. 2. 3. 4.]
 [5. 6. 0. 8.]]
float64


In [33]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
# create a numpy array of ones
y = np.ones((3,3),dtype=int)
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [39]:
# create an identity matrix
a = np.eye(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [43]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.00103364 0.67457816 0.49548384 0.57104675]
 [0.15256932 0.93491667 0.0487978  0.66518184]
 [0.99866645 0.42780204 0.66440756 0.4293246 ]]


In [44]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[84 83 70 76 12]
 [72 65 90 54 24]
 [46 37 31 53 24]]


In [54]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(0,100,5)
print(d)

[  0.  25.  50.  75. 100.]


In [56]:
# array of evenly spaced values --> specifying the step
e = np.arange(0,100,5)
print(e)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [64]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
a

array([[6, 2, 7],
       [3, 1, 1],
       [7, 4, 3]])

In [65]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[22 16 22]
 [19 13 17]
 [20 23 16]]
[[-10 -12  -8]
 [-13 -11 -15]
 [ -6 -15 -10]]
[[ 96  28 105]
 [ 48  12  16]
 [ 91  76  39]]
[[0.375      0.14285714 0.46666667]
 [0.1875     0.08333333 0.0625    ]
 [0.53846154 0.21052632 0.23076923]]


In [66]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 16 22]
 [19 13 17]
 [20 23 16]]
[[-10 -12  -8]
 [-13 -11 -15]
 [ -6 -15 -10]]
[[ 96  28 105]
 [ 48  12  16]
 [ 91  76  39]]
[[0.375      0.14285714 0.46666667]
 [0.1875     0.08333333 0.0625    ]
 [0.53846154 0.21052632 0.23076923]]


Array Manipulation

In [67]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 3 4]
 [9 4 4]]
(2, 3)


In [68]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[1 9]
 [3 4]
 [4 4]]
(3, 2)


In [69]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 3 6]
 [6 9 1]]
(2, 3)


In [70]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 3]
 [6 6]
 [9 1]]
(3, 2)


In [71]:
a = np.random.randint(0,10,(2,3))
a

array([[0, 3, 0],
       [6, 9, 6]])